extract:
  extractors:
    - type: copom_list
      params:
        request:
          url: "https://www.bcb.gov.br/api/servico/sitebcb/copom/atas"
          query_params:
            quantidade: 80 # 10 anos de reunioes (8 reunioes por ano)
    - type: copom_detail
      params:
        request:
          url: "https://www.bcb.gov.br/api/servico/sitebcb/copom/atas_detalhes"
          query_params: {}
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: rename_columns
      params:
        columns_mapping:
          nroReuniao: nro_reuniao
          dataReferencia: data_referencia
          dataPublicacao: data_publicacao
          textoAta: html_ata
    - type: html_to_text
      params:
        target_column: html_ata
        target_html_id: ataconteudo
        result_column: conteudo
    - type: select_columns
      params:
        columns:
          - nro_reuniao
          - data_referencia
          - data_publicacao
          - conteudo
load:
  partition_by: []