extract:
  base_url: "https://www.bcb.gov.br/api/servico/sitebcb/copom"
  endpoints:
    list: "atas"
    detail: "atas_detalhes"
  params: { quantidade: 40 } # 5 anos de reunioes (8 reunioes por ano)
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: rename_columns
      params:
        columns_mapping:
          nroReuniao: nro_reuniao
          dataReferencia: data_referencia
          dataPublicacao: data_publicacao
          textoAta: html_ata
    - type: html_to_text
      params:
        target_column: html_ata
        target_html_id: ataconteudo
        result_column: conteudo
    - type: select_columns
      params:
        columns:
          - nro_reuniao
          - data_referencia
          - data_publicacao
          - conteudo
load:
  partition_by: []