# Taxa de câmbio - Livre - Dólar americano (compra) - Média de período - mensal
# Unidade: u.m.c./US$
extract:
  extractors:
    - type: sgs
      params:
        periodicidade_diaria: false
        request:
          url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.3697/dados"
          query_params:
            formato: "json"
            dataInicial: "01/01/1998"
            dataFinal: "31/12/2025"
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: text_to_date
      params:
        target_column: data
        text_format: "%d/%m/%Y"
    - type: rename_columns
      params:
        columns_mapping:
          valor: cambio
load:
  partition_by: []