extract:
  url_listar: "https://www.bcb.gov.br/api/servico/sitebcb/copom/comunicados"
  url_detalhes: "https://www.bcb.gov.br/api/servico/sitebcb/copom/comunicados_detalhes"
  qtd_comunicados: 40 # 5 anos de reunioes (8 reunioes por ano)
load:
  bronze:
    partition_by: []