extract:
  extractors:
    - type: copom_list
      params:
        request:
          url: "https://www.bcb.gov.br/api/servico/sitebcb/copom/comunicados"
          query_params:
            quantidade: 80 # 10 anos de reunioes (8 reunioes por ano)
    - type: copom_detail
      params:
        request:
          url: "https://www.bcb.gov.br/api/servico/sitebcb/copom/comunicados_detalhes"
          query_params: {}
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: rename_columns
      params:
        columns_mapping:
          dataReferencia: data_referencia
          textoComunicado: html_comunicado
    - type: html_to_text
      params:
        target_column: html_comunicado
        result_column: conteudo
    - type: select_columns
      params:
        columns:
          - nro_reuniao
          - data_referencia
          - titulo
          - conteudo
load:
  partition_by: []