extract:
  extractors:
    - type: sgs
      params:
        request:
          url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.4380/dados"
          query_params:
            formato: "json"
            dataInicial: "01/01/2015"
            dataFinal: "31/12/2025"
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: text_to_date
      params:
        target_column: data
        text_format: "%d/%m/%Y"
    - type: rename_columns
      params:
        columns_mapping:
          valor: pib
load:
  partition_by: []