extract:
  extractors:
    - type: sgs
      params:
        request:
          url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.4189/dados"
          query_params:
            formato: "json"
            dataInicial: "01/01/1998"
            dataFinal: "31/12/2025"
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: text_to_date
      params:
        target_column: data
        text_format: "%d/%m/%Y"
    - type: percent_to_decimal
      params:
        target_column: valor
        result_column: selic
    - type: select_columns
      params:
        columns:
          - data
          - selic
load:
  partition_by: []