# Taxa de juros - Meta Selic definida pelo Copom
# Unidade: % a.a.
extract:
  extractors:
    - type: sgs
      params:
        periodicidade_diaria: true
        request:
          url: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.432/dados"
          query_params:
            formato: "json"
            dataInicial: "01/01/1998" #  Data Inicial segundo metadados do SGS: 05/03/1999
            dataFinal: "31/12/2025"
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: text_to_date
      params:
        target_column: data
        text_format: "%d/%m/%Y"
    - type: percent_to_decimal
      params:
        target_column: valor
        result_column: selic_meta
    - type: select_columns
      params:
        columns:
          - data
          - selic_meta
load:
  partition_by: []