extract:
  base_url: "https://api.bcb.gov.br"
  endpoints:
    data: "dados/serie/bcdata.sgs.11/dados"
  params:
    formato: "json"
    data_inicial: "01/01/2020"
    data_final: "31/12/2025"
transform:
  transformers:
    - type: json_to_dataframe
      params: {}
    - type: text_to_date
      params:
        target_column: data
        text_format: "%d/%m/%Y"
    - type: percent_to_decimal
      params:
        target_column: valor
        result_column: selic_diaria
    - type: select_columns
      params:
        columns:
          - data
          - selic_diaria
load:
  partition_by: []